In [3]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [4]:
# Import data
path = r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Original Data'

In [5]:
# Import the orders.csv dataset using the os library and vars_list, excluding the eval_set column
path = r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis'
df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders.csv'), index_col=False)

In [6]:
# Import the products.csv file using the path variable and os library, and store it as df_prods
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'products.csv'), index_col=False)

In [7]:
# Remove the "eval_set" column from “orders.csv”
df_ords.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [8]:
df_ords['days_since_prior_order'].value_counts(dropna=False)

days_since_prior_order
30.0    369323
7.0     320608
6.0     240013
4.0     221696
3.0     217005
5.0     214503
NaN     206209
2.0     193206
8.0     181717
1.0     145247
9.0     118188
14.0    100230
10.0     95186
13.0     83214
11.0     80970
12.0     76146
0.0      67755
15.0     66579
16.0     46941
21.0     45470
17.0     39245
20.0     38527
18.0     35881
19.0     34384
22.0     32012
28.0     26777
23.0     23885
27.0     22013
24.0     20712
25.0     19234
29.0     19191
26.0     19016
Name: count, dtype: int64

In [9]:
df_ords.rename(columns = {'order_dow' : 'orders_day_of_week'}, inplace = True)

In [10]:
df_ords.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [11]:
df_ords['order_id'] = df_ords['order_id'].astype('str')

In [12]:
df_ords['order_id'].dtype

dtype('O')

In [13]:
# Import dataset departments.csv as df_dep
df_dep = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'departments.csv'), index_col=False)

In [14]:
df_dep.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [15]:
# Transpose df_dep
df_dep.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [16]:
# Create a new dataframe from the transposed version
df_dep_t = df_dep.T

In [17]:
df_dep_t

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [18]:
df_dep_t.reset_index()

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

In [19]:
# Take first row of df_dep_t for the header
new_header = df_dep_t.iloc[0]

In [20]:
new_header

0    department
Name: department_id, dtype: object

In [21]:
# Create a new dataframe that only copies over rows beyond the first row
df_dep_t_new = df_dep_t[1:]

In [22]:
df_dep_t_new

                  0
1            frozen
2             other
3            bakery
4           produce
5           alcohol
6     international
7         beverages
8              pets
9   dry goods pasta
10             bulk
11    personal care
12     meat seafood
13           pantry
14        breakfast
15     canned goods
16       dairy eggs
17        household
18           babies
19           snacks
20             deli
21          missing

In [23]:
# Set header row as the df header
df_dep_t_new.columns = new_header

In [24]:
df_dep_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [25]:
# Turn df_dep_t_new dataframe into a dictionary
data_dict = df_dep_t_new.to_dict('index')

In [26]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [27]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [28]:
# Use data dictionary to determine what the number stands for
print(data_dict.get('19'))

{'department': 'snacks'}

In [29]:
# Create a subset for your df_prods dataframe that only contains data from the snacks department
df_snacks = df_prods[df_prods['department_id']==19]

In [30]:
df_prods[df_prods['department_id']==19]

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5
...,...,...,...,...,...
49666,49662,Bacon Cheddar Pretzel Pieces,107,19,3.6
49669,49665,Super Dark Coconut Ash & Banana Chocolate Bar,45,19,6.9
49670,49666,Ginger Snaps Snacking Cookies,61,19,5.2
49675,49671,Milk Chocolate Drops,45,19,3.0
49683,49679,Famous Chocolate Wafers,61,19,6.0

In [31]:
# Check df_snacks
df_snacks.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5

In [32]:
# Second way of creating a subset
df_snacks_2 = df_prods.loc[df_prods['department_id'] == 19]

In [33]:
# Third way of creating a subset
df_snacks_3 = df_prods.loc[df_prods['department_id'].isin([19])]

# Task 4.4

## 2 Find another identifier variable in the df_ords dataframe that doesn’t need to be included in your analysis as a numeric variable and change it to a suitable format.

In [36]:
### Check for identifier columns in df_ords
df_ords.dtypes

order_id                   object
user_id                     int64
eval_set                   object
order_number                int64
orders_day_of_week          int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [37]:
### Convert 'user_id' to string type
df_ords['user_id'] = df_ords['user_id'].astype('str')

In [38]:
### Verify the change
print(df_ords.dtypes)

order_id                   object
user_id                    object
eval_set                   object
order_number                int64
orders_day_of_week          int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

## 3 Look for a variable in your df_ords dataframe with an unintuitive name and change its name without overwriting the dataframe.

In [40]:
### Rename 'order_hour_of_day' to 'order_time' without overwriting the dataframe
df_ords_renamed = df_ords.rename(columns={'order_hour_of_day': 'order_time'})

In [41]:
### Check the name change
df_ords_renamed

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_time,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

## 4 Your client wants to know what the busiest hour is for placing orders. Find the frequency of the corresponding variable and share your findings.

In [43]:
### Find the frequency of orders by 'order_hour_of_day'
order_hour_frequency = df_ords['order_hour_of_day'].value_counts().sort_index()

In [44]:
### Display the frequencies for each hour
print(order_hour_frequency)

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [45]:
### Find the busiest hour by identifying the hour with the maximum number of orders
busiest_hour = order_hour_frequency.idxmax()
busiest_hour_orders = order_hour_frequency.max()

In [46]:
### Display the busiest hour and the number of orders
print(f"The busiest hour for placing orders is {busiest_hour} with {busiest_hour_orders} orders.")

The busiest hour for placing orders is 10 with 288418 orders.

In [47]:
## 5 Determine the meaning behind a value of 4 in the "department_id" column within the df_prods dataframe using a data dictionary
print(data_dict.get('4'))

{'department': 'produce'}

In [48]:
## 6 Create a subset for breakfast items (department_id = 14)
df_breakfast = df_prods[df_prods['department_id'] == 14]

In [49]:
### Check df_breakfast
df_breakfast.head()

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6

## 7 They’d also like to see details about products that customers might use to throw dinner parties. Your task is to find all observations from the entire dataframe that include items from the following departments: alcohol, deli, beverages, and meat/seafood. You’ll need to present this subset to your client.

In [51]:
### Create a list of department_ids for dinner party items
dinner_party_departments = [5, 20, 7, 12]

In [52]:
### Filter the df_prods DataFrame to include only these departments
df_dinner_party = df_prods[df_prods['department_id'].isin(dinner_party_departments)]

In [53]:
### Check df_dinner_party
df_dinner_party

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
...,...,...,...,...,...
49676,49672,Cafe Mocha K-Cup Packs,26,7,6.5
49679,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7,14.0
49680,49676,Ultra Red Energy Drink,64,7,14.5
49686,49682,California Limeade,98,7,4.3
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3

## 8 It’s important that you keep track of total counts in your dataframes. How many rows does the last dataframe you created have?
7650 rows

## 9 Someone from the data engineers team in Instacart thinks they’ve spotted something strange about the customer with a "user_id" of “1.” Extract all the information you can about this user.

In [56]:
### Filter the df_ords DataFrame for the user with user_id '1'
df_user_1 = df_ords[df_ords['user_id'] == '1']

In [57]:
### Display the first few rows of the data for this user
print(df_user_1.head())

  order_id user_id eval_set  order_number  orders_day_of_week  \
0  2539329       1    prior             1                   2
1  2398795       1    prior             2                   3
2   473747       1    prior             3                   3
3  2254736       1    prior             4                   4
4   431534       1    prior             5                   4

   order_hour_of_day  days_since_prior_order
0                  8                     NaN
1                  7                    15.0
2                 12                    21.0
3                  7                    29.0
4                 15                    28.0

In [58]:
### Display summary information about this user
print(df_user_1.describe(include='all'))

       order_id user_id eval_set  order_number  orders_day_of_week  \
count        11      11       11     11.000000           11.000000
unique       11       1        2           NaN                 NaN
top     2539329       1    prior           NaN                 NaN
freq          1      11       10           NaN                 NaN
mean        NaN     NaN      NaN      6.000000            2.636364
std         NaN     NaN      NaN      3.316625            1.286291
min         NaN     NaN      NaN      1.000000            1.000000
25%         NaN     NaN      NaN      3.500000            1.500000
50%         NaN     NaN      NaN      6.000000            3.000000
75%         NaN     NaN      NaN      8.500000            4.000000
max         NaN     NaN      NaN     11.000000            4.000000

        order_hour_of_day  days_since_prior_order
count           11.000000               10.000000
unique                NaN                     NaN
top                   NaN                     NaN
freq                  NaN                     NaN
mean            10.090909               19.000000
std              3.477198                9.030811
min              7.000000                0.000000
25%              7.500000               14.250000
50%              8.000000               19.500000
75%             13.000000               26.250000
max             16.000000               30.000000

## 10 You also need to provide some details about this user’s behavior. What basic stats can you provide based on the information you have?

In [60]:
### 1. Total number of orders placed by the user
total_orders = df_user_1['order_number'].nunique()

### 2. Most frequent order hour
most_frequent_hour = df_user_1['order_hour_of_day'].mode()[0]

### 3. Most frequent day of the week for orders
most_frequent_day = df_user_1['orders_day_of_week'].mode()[0]

### 4. Average days since prior order
average_days_between_orders = df_user_1['days_since_prior_order'].mean()

### 5. Min and max days since prior order (to identify any unusually long or short gaps)
min_days_between_orders = df_user_1['days_since_prior_order'].min()
max_days_between_orders = df_user_1['days_since_prior_order'].max()

### 6. Display the basic statistics
print(f"User 1 placed {total_orders} orders.")
print(f"The most frequent order hour is {most_frequent_hour}.")
print(f"The most frequent day of the week for orders is {most_frequent_day}.")
print(f"The average days between orders is {average_days_between_orders:.2f} days.")
print(f"The minimum days between orders is {min_days_between_orders} days.")
print(f"The maximum days between orders is {max_days_between_orders} days.")

User 1 placed 11 orders.
The most frequent order hour is 7.
The most frequent day of the week for orders is 4.
The average days between orders is 19.00 days.
The minimum days between orders is 0.0 days.
The maximum days between orders is 30.0 days.

In [61]:
## 12 Export your df_ords dataframe as “orders_wrangled.csv” in your “Prepared Data” folder.
df_ords.to_csv(os.path.join(path, '02 Data','Prepared Data', 'orders_wrangled.csv'))

In [62]:
## 13 Export the df_dep_t_new dataframe as “departments_wrangled.csv” in your “Prepared Data” folder so that you have a “.csv” file of your departments data in the correct format.
df_dep_t_new.to_csv(os.path.join(path, '02 Data','Prepared Data', 'departments_wrangled.csv'))

In [117]:
df_ords.shape

(3421083, 7)