In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Import the products.csv file as df_prods
df_prods = pd.read_csv(r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Original Data\products.csv', index_col=False)

In [3]:
# Import the orders_checked.csv file as df_ords
df_ords = pd.read_csv(r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Prepared Data\orders_checked.csv', index_col=0)

In [4]:
df_ords.describe()

,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06
mean,1.715486e+01,2.776219e+00,1.345202e+01,1.044488e+01
std,1.773316e+01,2.046829e+00,4.226088e+00,9.308727e+00
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [5]:
df_prods.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [6]:
# Create a data frame
df_test = pd.DataFrame ()

In [7]:
# Create a mixed type column
df_test['mix'] = ['a', 'b', 1, True]

In [8]:
df_test.head()

    mix
0     a
1     b
2     1
3  True

In [9]:
# Check the data type of the new data frame
for col in df_test.columns.tolist():
  weird = (df_test[[col]].applymap(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_test[weird]) > 0:
    print (col)

mix

C:\Users\User\AppData\Local\Temp\ipykernel_4032\4146718827.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_test[[col]].applymap(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)

In [10]:
# Change the data type from mix to string
df_test['mix'] = df_test['mix'].astype('str')

In [11]:
# Find missing values in df_prods
df_prods.isnull().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [12]:
# Create a subset of the dataframe containing only the values in question
df_nan = df_prods[df_prods['product_name'].isnull() == True]

In [13]:
# View the missing values
df_nan

       product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14    12.2
68             69          NaN        26              7    11.8
115           116          NaN        93              3    10.8
261           262          NaN       110             13    12.1
525           525          NaN       109             11     1.2
1511         1511          NaN        84             16    14.3
1780         1780          NaN       126             11    12.3
2240         2240          NaN        52              1    14.2
2586         2586          NaN       104             13    12.4
3159         3159          NaN       126             11    13.1
3230         3230          NaN       120             16    14.4
3736         3736          NaN        41              8    14.8
4283         4283          NaN        77              7    14.4
4790         4790          NaN        91             16    14.5
38187       38183          NaN        39             12    20.9
40444       40440          NaN       120             16    14.8

In [14]:
# Check your current data frame
df_prods.shape

(49693, 5)

In [15]:
# Adress the missing values, view only the non-missing values
df_prods_clean = df_prods[df_prods['product_name'].isnull() == False]

In [16]:
# Check that the number of rows has decreased
df_prods_clean.shape

(49677, 5)

In [17]:
# Look for full duplicates within your dataframe
df_dups = df_prods_clean[df_prods_clean.duplicated()]

In [18]:
# Display all the duplicate rows within your dataframe.
df_dups

,product_id,product_name,aisle_id,department_id,prices
462,462,Fiber 4g Gummy Dietary Supplement,70,11,4.8
18459,18458,Ranger IPA,27,5,9.2
26810,26808,Black House Coffee Roasty Stout Beer,27,5,13.4
35309,35306,Gluten Free Organic Peanut Butter & Chocolate ...,121,14,6.8
35495,35491,Adore Forever Body Wash,127,11,9.9

In [19]:
# Check the current number of rows in your df_prods_clean dataframe
df_prods_clean.shape

(49677, 5)

In [20]:
# Create a new dataframe that doesn’t include the duplicates you just identified using the drop_duplicates() function
df_prods_clean_no_dups = df_prods_clean.drop_duplicates()

In [21]:
# Check that the number of rows has decreased
df_prods_clean_no_dups.shape

(49672, 5)

In [22]:
# Export the cleaned df_prods_clean_no_dups into products_checked.csv
df_prods_clean_no_dups.to_csv(r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Prepared Data\products_checked.csv', index=False)

Task 4.5

In [24]:
# 2 Run the df.describe() function on your df_ords dataframe
df_ords.describe()

,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06
mean,1.715486e+01,2.776219e+00,1.345202e+01,1.044488e+01
std,1.773316e+01,2.046829e+00,4.226088e+00,9.308727e+00
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

# Interpretation of the output
order_number: The maximum value of 100 suggests some users have placed many orders, which may be normal if the data spans a long period.

days_since_prior_order: The minimum of 0 likely represents same-day orders or first-time orders, both reasonable. The maximum of 30 might mean that any gap beyond 30 days isn’t recorded, so it’s worth confirming the meaning of the maximum value (30).

In [26]:
# 3 Check for mixed-type data in your df_ords dataframe
for col in df_ords.columns.tolist():
    weird = (df_ords[[col]].map(type) != df_ords[[col]].iloc[0].map(type)).any(axis=1)
    if weird.any():
        print(col)

# 4 If you find mixed-type data, fix it
No mixed-type data found

In [28]:
# 5 Run a check for missing values in your df_ords dataframe
df_ords.isnull().sum()

eval_set                  0
order_number              0
orders_day_of_week        0
order_hour_of_day         0
days_since_prior_order    0
dtype: int64

In [29]:
df_ords.head(50)

,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
user_id,,,,,
1,prior,1,2,8,0.0
1,prior,2,3,7,15.0
1,prior,3,3,12,21.0
1,prior,4,4,7,29.0
1,prior,5,4,15,28.0
1,prior,6,2,7,19.0
1,prior,7,1,9,20.0
1,prior,8,1,14,14.0
1,prior,9,1,16,0.0
1,prior,10,4,8,30.0
1,train,11,4,8,14.0
2,prior,1,2,11,0.0
2,prior,2,5,10,10.0
2,prior,3,1,10,3.0
2,prior,4,2,10,8.0
2,prior,5,3,11,8.0
2,prior,6,2,9,13.0
2,prior,7,2,12,14.0
2,prior,8,1,15,27.0
2,prior,9,2,9,8.0
2,prior,10,1,11,6.0
2,prior,11,1,10,30.0
2,prior,12,1,9,28.0
2,prior,13,4,11,30.0
2,prior,14,3,10,13.0
2,train,15,1,11,30.0
3,prior,1,1,14,0.0
3,prior,2,3,19,9.0
3,prior,3,3,16,21.0
3,prior,4,2,18,20.0
3,prior,5,0,17,12.0
3,prior,6,0,16,7.0
3,prior,7,0,15,7.0
3,prior,8,0,17,7.0
3,prior,9,0,16,7.0
3,prior,10,3,16,17.0
3,prior,11,0,18,11.0
3,prior,12,1,15,15.0
3,test,13,5,15,11.0
4,prior,1,6,11,0.0
4,prior,2,4,11,19.0
4,prior,3,4,15,21.0
4,prior,4,5,13,15.0
4,prior,5,5,13,0.0
4,test,6,3,12,30.0
5,prior,1,3,12,0.0
5,prior,2,0,16,11.0
5,prior,3,3,18,10.0
5,prior,4,1,18,19.0
5,train,5,0,11,6.0

# In a markdown cell, report your findings and propose an explanation for any missing values you find.
days_since_prior_order: 206,209 missing values
Looking at the first 50 rows of the dataframe above, it is clear that the NaN values represent the first order made by each user. 
Given that the NaN values represent the first order made by each user, imputing these with 0.0 is indeed a sensible approach. 
This explicitly indicates "no prior order" and aligns well with the data’s structure (the existing zeros).
The zeros in this data frame will represent either no prior order or cases where the user made consecutive orders without any gap.

In [31]:
# 6 Address the missing values using an appropriate method.
df_ords_imputed = df_ords.copy()
df_ords_imputed['days_since_prior_order'] = df_ords_imputed['days_since_prior_order'].fillna(0)

In [32]:
# Check if everything is correct
df_ords_imputed.head(50)

,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
user_id,,,,,
1,prior,1,2,8,0.0
1,prior,2,3,7,15.0
1,prior,3,3,12,21.0
1,prior,4,4,7,29.0
1,prior,5,4,15,28.0
1,prior,6,2,7,19.0
1,prior,7,1,9,20.0
1,prior,8,1,14,14.0
1,prior,9,1,16,0.0
1,prior,10,4,8,30.0
1,train,11,4,8,14.0
2,prior,1,2,11,0.0
2,prior,2,5,10,10.0
2,prior,3,1,10,3.0
2,prior,4,2,10,8.0
2,prior,5,3,11,8.0
2,prior,6,2,9,13.0
2,prior,7,2,12,14.0
2,prior,8,1,15,27.0
2,prior,9,2,9,8.0
2,prior,10,1,11,6.0
2,prior,11,1,10,30.0
2,prior,12,1,9,28.0
2,prior,13,4,11,30.0
2,prior,14,3,10,13.0
2,train,15,1,11,30.0
3,prior,1,1,14,0.0
3,prior,2,3,19,9.0
3,prior,3,3,16,21.0
3,prior,4,2,18,20.0
3,prior,5,0,17,12.0
3,prior,6,0,16,7.0
3,prior,7,0,15,7.0
3,prior,8,0,17,7.0
3,prior,9,0,16,7.0
3,prior,10,3,16,17.0
3,prior,11,0,18,11.0
3,prior,12,1,15,15.0
3,test,13,5,15,11.0
4,prior,1,6,11,0.0
4,prior,2,4,11,19.0
4,prior,3,4,15,21.0
4,prior,4,5,13,15.0
4,prior,5,5,13,0.0
4,test,6,3,12,30.0
5,prior,1,3,12,0.0
5,prior,2,0,16,11.0
5,prior,3,3,18,10.0
5,prior,4,1,18,19.0
5,train,5,0,11,6.0

In [33]:
# 7 Run a check for duplicate values in your df_ords data
df_ords_imputed_dups = df_ords_imputed[df_ords_imputed.duplicated()]

In [34]:
# Display all the duplicate rows within your dataframe.
df_ords_imputed_dups

,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
user_id,,,,,
16,prior,1,2,8,0.0
21,prior,1,1,10,0.0
21,prior,15,1,9,7.0
21,prior,21,1,9,7.0
23,prior,4,3,11,30.0
...,...,...,...,...,...
206209,prior,10,5,18,29.0
206209,prior,11,4,10,30.0
206209,prior,12,1,12,18.0
206209,prior,13,1,12,7.0
206209,train,14,6,14,30.0

Since df_ords_imputed_dups displays only column headers without any rows, it indicates that no duplicate rows were found, meaning the dataframe is empty. 
To confirm whether df_ords_dups is empty, I can check by running:

In [36]:
df_ords_imputed_dups.shape

(3089321, 5)

If this command returns (0, 7), it confirms that no duplicates were detected.

# 8 Address the duplicates using an appropriate method
No duplicates were found in the `df_ords` dataframe. However, if duplicates had been detected, I would create a new dataframe without these duplicates by running:

df_ords_imputed_no_dups = df_ords_imputed_dups.drop_duplicates()

To confirm the duplicates were removed, I would compare the number of rows in `df_ords` before and after running this code by checking df_ords_imputed.shape and df_ords_imputed_no_dups.shape. A reduction in rows would indicate that duplicates were successfully removed.

In [39]:
# Export df_ords_imputed_dups into orders_checked.csv
df_ords_imputed.to_csv(r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis\02 Data\Prepared Data\orders_checked.csv', index=False)