In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Define the path to the pickle file
path = r'C:\Users\User\Documents\Career Foundry\Data Analytics Immersion\Data Immersion 4. Python Fundamentals for Data Analysts\Instacart Basket Analysis'
file_path = os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_combined.pkl')

In [3]:
# 3 Import the orders_products_combined dataframe from the pickle file
orders_products_combined = pd.read_pickle(file_path)

In [4]:
# Verify
orders_products_combined.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,prior,1,2,8,NaN,196,1,0,both
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both

In [5]:
# 4 Check the shape of the imported dataframe
orders_products_combined.shape

(32434489, 11)

In [6]:
# Import the products.csv file using the path variable and os library, and store it as df_prods
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'products_checked.csv'), index_col=False)

In [7]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [8]:
# Rename the existing '_merge' column in orders_products_combined if it exists
if '_merge' in orders_products_combined.columns:
    orders_products_combined = orders_products_combined.rename(columns={'_merge': 'existing_merge_status'})

In [9]:
# 5 Merged the two data frames
ords_prods_merge = orders_products_combined.merge(df_prods, on = 'product_id', indicator = True)

In [10]:
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,existing_merge_status,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

In [11]:
# 6 Check the value counts of the merge flag
ords_prods_merge['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [12]:
# 7 Export the newly created dataframe as ords_prods_merge in a suitable format
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))